apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: jenkinsdevops
        image: truthaniket/jenkinsdevops:latest
        ports:
        - containerPort: 80

